### ISSUE TITLE
Make plan2nix respect revisions

### ISSUE THREAD

**Issue by arianvp** [angerman/nix-tools#21]
Currently it seems to always choose revision `0` which is wrong. We should choose the revision the plan uses.   however the plan doesnt export this information. I made a PR such that cabal does output this information: https://github.com/haskell/cabal/pull/5695

**Comment by ElvishJerricco** [comment]
FWIW, plan2nix *should* be selecting the *latest* revision in the Hackage index, not revision 0.

**Comment by arianvp** [comment]
Im sorry. I misread.  the code seems to always set revision to `Nothing` at this moment. Which causes it to set to the `default` revision.

**Comment by arianvp** [comment]
Ok in that case we can just close this issue :)
